Solved duplicate value label problem.
Solved error due to duplicate value labels: Error was...

```Python
ValueError: Value labels for column stat_s are not unique. The repeated labels are:
```